In [71]:
import numpy as np

In [72]:
#Creating simple array
arr = np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
#Get a value at in index
arr[8]

8

In [74]:
#get a value in a range
arr[1:5]

array([1, 2, 3, 4])

In [75]:
#Setting avakue at index range
arr[0:5] = 100
#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [76]:
#Resrt array, we'll see why i had to reset in a moment
arr = np.arange(0,11)
#Show 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
#Important notes on slices 
slice_of_arr = arr[0:6]
#Show slice_of_arr
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [78]:
#Change slice
slice_of_arr [:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [79]:
#Now note the change also occur in our original array
arr
#Data is not copied, it's a view of the original array! this avoid memory problem!  

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
#To get a copied need to be explicit
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
#Indexing a 2D array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [83]:
#Format in arr_2d[row][col] on arr_2d[row][col]
#Getting individual element value
arr_2d[1][0]

20

In [84]:
#2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [86]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [87]:
#Fancy indexing
#set up matrix
arr2d = np.zeros((10,10))

In [98]:
#Length of array
arr_length = arr2d.shape[1]

In [99]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [100]:
#Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [101]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
M = np.ones((2,3))
N = np.ones((3,2))
a = np.arange(3)

In [91]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
a

array([0, 1, 2])

In [93]:
a+M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [94]:
N


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [95]:
a[:,np.newaxis]+N

array([[1., 1.],
       [2., 2.],
       [3., 3.]])