In [20]:
#Creating Numpy arrays
import numpy as np

#Converting from a list
#Lets start with a list
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)

In [13]:
#Print out array
print my_array1

[1 2 3 4]


In [27]:
#Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make a multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [29]:
#Lets get the size of the array
my_array2.shape

(2L, 4L)

In [31]:
#Find out the data type of the array
my_array2.dtype

dtype('int32')

In [33]:
#Making special case array

#Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
#Ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
#An empy array
np.empty(5)
np.empty((3,4))

array([[5.50997976e-316, 5.50992522e-316, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.11443817e+179, 1.46197141e+165,
        1.04890844e-042],
       [6.52398999e-038, 1.46442325e-075, 1.04069924e-071,
        5.40151995e-038]])

In [40]:
#Identity array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])