In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Tacking squar roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
#Calaculating exponential(e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
#Binary functions require two arrays
#random array(normal dist)
A = np.random.randn(10)
A

array([-1.92778562, -0.87091262, -2.07395939, -0.20891688, -1.30917622,
       -0.05781726,  0.99559937, -0.46531291,  0.26843004,  0.04390141])

In [10]:
B = np.random.randn(10)
B

array([-1.21743492, -2.08744203,  0.8976867 , -0.54789081, -0.13219194,
       -3.16925169, -0.85057184, -0.41844972, -1.12485019, -0.38124617])

In [11]:
#Addition
np.add(A,B)

array([-3.14522054, -2.95835465, -1.17627269, -0.75680768, -1.44136816,
       -3.22706895,  0.14502754, -0.88376263, -0.85642014, -0.33734476])

In [12]:
#Finding max or min between two arrays
np.maximum(A,B)


array([-1.21743492, -0.87091262,  0.8976867 , -0.20891688, -0.13219194,
       -0.05781726,  0.99559937, -0.41844972,  0.26843004,  0.04390141])

In [13]:
#For full and entensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True