In [53]:
import numpy as np

In [54]:
arr = np.arange(5)

In [55]:
#Saving array on disk in binary format(file ectension.npy)
np.save('my_array',arr)

In [56]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [58]:
#Saving multipile arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [59]:
archive_array = np.load('two_arrays.npz')
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
#Now lets remove them from the memory
#?

In [61]:
#Now saving and loading text files
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter='.')



In [62]:
arr = np.loadtxt('my_test_text.txt',delimiter='.')
arr

array([[1., 0., 2., 0., 3., 0.],
       [4., 0., 5., 0., 6., 0.]])